name: CMake Windows

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '*.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:

  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
   
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        target: 'desktop'
        setup-python: 'false'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/cmake_vs -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/cmake_vs --config ${{env.BUILD_TYPE}}

    - name: Build Installer
      working-directory: res\installer
      run: ISCC.exe joystick2vc.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: joystick2vc
        path: 'res\installer\output\**'

    - name: Create prerelease2
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        tag_name: "ci_win"
        name: "${{ steps.version.outputs.version }}"
        files: ./res/installer/output/*.exe
      
#    - name: Create prerelease
#      if: github.ref == 'refs/heads/main'
#      uses: marvinpinto/action-automatic-releases@latest
#      with:
#        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        prerelease: true
#        automatic_release_tag: "ci_win"
#        title: "${{ steps.version.outputs.version }}"
#        files: |        
#          ./res/installer/output/*.exe
